# postgres service with a table named 'blog' and a user named 'blog' with password 'blog'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IS_DEV=false
    ports:
      - "8000:8000"

    depends_on:
      - postgres
    volumes:
      - .:/app
    command: ["poetry", "run", "python", "-m", "app"]

    networks:
      - my_network
volumes:
  postgres-data:

networks:
  my_network: