# postgres service with a table named 'blog' and a user named 'blog' with password 'blog'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:
